version: "3.9"

services:
  simplescan:
    container_name: simplescan-web
    hostname: simplescan-web
    image: simplescan-web:latest
    restart: unless-stopped
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: 'Europe/Kyiv'
    volumes:
      - "/home/User/Desktop/Scanner-Docs:/config/images"  # Change the host path to your own directory for saving scanned images
    ports:
      - "5800:5800" # Access via browser: http://<your-host-ip>:5800
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true  # Required for scanner hardware access
